### ISSUE TITLE
Icon for Switcheroo

### ISSUE THREAD

**Issue by teccheck** [budde25/switcheroo#11]
Hey there, I just had an idea for a good icon. Hope you like it :)

![switcheroo](https://user-images.githubusercontent.com/25465306/228496125-1b563b58-caa4-4a9e-b587-3e10a5ee0d25.png)

SVG:
![switcheroo_opt](https://user-images.githubusercontent.com/25465306/228496341-e67a7d69-1efa-4f09-b322-1f288ce6531c.svg)

**Comment by budde25** [comment]
That looks great! I'll update the images in the repo with this and publish a new release soonish. Thank you!

**Comment by teccheck** [comment]
Awesome!

**Comment by budde25** [comment]
Thanks for making the Icon! I just published the new release v0.6.0 that has it!
It looks great!
